#Arrays and Vectors

The Python types we've seen so far are all *built-in* to Python.  This means that they're automatically available when you start writing Python code.  As with any modern language, however, programmers are always adding new functionality to Python and they often want to share their code with others.  The main way this is done is with packages.

A package contains extra object types, functions, and variables that are not included in base Python.  Some packages are specialized to niche applications, while others are so popular that nearly every coder uses them.

Now one particular package, numpy, sits as the foundation for scientific and data computing in python. Many other data science packages are built on top of numpy, so it's very important to understand its function.

[Numpy](http://www.numpy.org/) is the core of the [pydata](http://pydata.org/) ecosystem.

------

*From the Numpy Website*

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

------

We'll often use numpy to work with data.  In this notebook, we'll begin introducing its functionality with a few simple examples.

To use the functionality provided by a package, we first have to import it into our program.  This is done with the import keyword.  At the point at which we import a package, we can also rename it with the `as` keyword. Traditionally, numpy is renamed to np. The reason that we do this is that there is a convention in the pydata community to import data packages with shorter names.


In [6]:
import numpy as np

In [7]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Now this should look pretty familiar; the arange function is analogous to the range function we saw earlier.  Instead of returning a range, however, this function returns something we call an array.

Arrays are similar to the sequences we saw earlier.  For example, we can access items by their indices.

In [8]:
my_array = np.arange(20)
my_array[2] = 12
my_array

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Arrays also have some unique characteristics.  For one thing, all the objects contained in an array must be the same type.  This may seem like a pesky restriction, but it allows arrays to work very efficiently on large amounts of data.

In [9]:
my_array[5] = "shoe"

ValueError: invalid literal for int() with base 10: 'shoe'

The data type of an array can be accessed through the dtype property, this will give us information about all the objects stored in the array. That means that you can't change the type of an array once it's created (unless you work around this).

In [10]:
my_array.dtype

dtype('int64')

Another thing about arrays is that once they're created, their size is fixed. You can't pop or append to an array. That's because of the way that arrays allocate memory under the hood. The fixed size allows arrays to be optimized for high performance.

In [11]:
new_array = np.array([5,10,15,20])

In [12]:
new_array.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [13]:
new_array.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

You can see in the error messages that the arrays we're dealing with have type `'numpy.ndarray'`. This stands for n-dimensional array.  We can make n anything that we want.

For example, we can create a 2-dimensional matrix with normally distributed random numbers between 0 and 1.

In [14]:
np.random.rand(5,5)

array([[ 0.3485017 ,  0.17995236,  0.3595112 ,  0.22129269,  0.70095449],
       [ 0.24573702,  0.25872806,  0.42839541,  0.71419389,  0.54417784],
       [ 0.79930945,  0.86196549,  0.85641477,  0.61529105,  0.89150267],
       [ 0.6562489 ,  0.1239075 ,  0.43037002,  0.59389352,  0.34547663],
       [ 0.28295824,  0.84908176,  0.79929516,  0.48377836,  0.32917841]])

Or a 3 dimensional cube of numbers.

In [26]:
np.random.rand(5,5,5)

array([[[ 0.84272158,  0.83679704,  0.5257461 ,  0.73736653,  0.45110009],
        [ 0.13841672,  0.10757949,  0.63145918,  0.16771083,  0.64128712],
        [ 0.80698612,  0.78004934,  0.78796473,  0.47922827,  0.70641219],
        [ 0.43528213,  0.65893285,  0.67785015,  0.64606294,  0.3998132 ],
        [ 0.65588931,  0.65056016,  0.53237286,  0.18387084,  0.3339849 ]],

       [[ 0.5422109 ,  0.44219767,  0.39250136,  0.47459834,  0.69258357],
        [ 0.91240791,  0.96729439,  0.14329598,  0.06610903,  0.16365455],
        [ 0.27483066,  0.84626304,  0.71325868,  0.82706608,  0.43683008],
        [ 0.30363783,  0.93689354,  0.72157754,  0.08772284,  0.57431791],
        [ 0.77952137,  0.60743034,  0.98645455,  0.33540844,  0.53469506]],

       [[ 0.89680185,  0.15110855,  0.43264088,  0.74135463,  0.14078825],
        [ 0.34220042,  0.53011661,  0.90455791,  0.25400812,  0.01920023],
        [ 0.93290593,  0.18418512,  0.43427611,  0.9612554 ,  0.45270675],
        [ 0.61656425,

We can keep going to higher and higher dimensional spaces, but doing so is outside the scope of this course.

I hope you're starting to see the power of numpy and what it allows you to do. Let dive in a bit deeper and see if we can't figure out some other cools functions NumPy has in store for us.



The NumPy library is huge and no class could truly cover it all, in addition, it's has a "partner" library,SciPy (for scientific python), that builds even further on NumPy. Let's play around with NumPy to realize a bit more of the power.

First let's generate some random variables.

In [24]:
np.random?

We can see that there are a variety of functions at our disposal. We've got all sorts of random variables. Which, mathematically, map from probability space to a number space. Let's start off my getting a bunch of normally distributed random variables.

In [27]:
np.random.randn(20)

array([-0.37930757,  1.37538244,  0.41835287,  0.07467508,  0.07084404,
        0.69637896, -1.11407639,  1.3812167 ,  0.22986012,  0.70550322,
        1.32124292,  0.47818417,  1.00462055, -2.64293399,  0.61211059,
        0.07565507, -1.12787497,  1.15320694, -2.24614077, -0.13124562])

So simple, now let's reshape it into a matrix. It's as simple as the reshape command.

In [30]:
np.random.randn(20).reshape(5,4)

array([[-0.19982669, -1.55407586, -0.3698846 ,  0.81249391],
       [-0.65108175, -1.36188201,  1.67887194, -0.61276092],
       [-2.35716335,  2.43604194,  0.30002732,  1.07182352],
       [-0.98120481, -0.47671355, -0.83111572,  0.57815578],
       [-2.27986753,  0.72769396, -0.21231002,  0.32579555]])

Now when you're working with data, many times you're going to want to calculate some statistics about it. What's awesome about numpy arrays is that they have a lot of these functions baked into the class. We're going to be learning about classses in chapter 6.

In [36]:
ar = np.random.randn(20).reshape(5,4)

In [37]:
ar

array([[ 0.67035513,  0.73542613,  0.1297458 ,  0.88661091],
       [ 0.07914825, -0.39407917, -0.71625645, -0.53719613],
       [-0.20092974,  1.57420947, -1.32530819,  1.34538317],
       [ 0.20595162,  3.02187901, -0.80776742,  0.11477428],
       [ 0.14477614, -0.76935721, -0.25621458,  0.17814124]])

For example, let's get the mean of this array.

In [38]:
ar.mean()

0.20396461238993449

The standard deviation is just as easy.

In [41]:
ar.std()

0.96331100760399779

Of course sometime we're going to want to do these operations on columns only or on the rows. Doing so is still extremely easy.

Here are our columns

In [35]:
ar.mean(axis=0)

array([-0.08367184,  0.38935699, -0.39893097,  0.43886695])

Here are our rows.

In [42]:
ar.mean(axis=1)

array([ 0.60553449, -0.39209588,  0.34833868,  0.63370937, -0.1756636 ])

We're going to be diving into all this information much more later, so I don't want to spoil the surprise but arrays and the work of the Pydata team have done wonderful things for the python ecosystem. When we're working with these libraries we're truly standing on the shoulders of giants.